### ISSUE TITLE
Error "No such file or directory: 'build.py'"

### ISSUE THREAD

**Issue by gnithin** [forexample/ios-dynamic-framework#2]
Hi,
Running the following from the readme raises an error - 
```
$ ./jenkins.py --toolchain ios-8-2
[/Users/nithin.g/myspace/ios-dynamic-framework]> "which" "cmake"
/usr/local/bin/cmake
[/Users/nithin.g/myspace/ios-dynamic-framework]> "cmake" "--version"
cmake version 3.7.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[/Users/nithin.g/myspace/ios-dynamic-framework]> "build.py" "--home" "Foo" "--toolchain" "ios-8-2" "--verbose" "--install" "--config" "Release"
Traceback (most recent call last):
  File "./jenkins.py", line 66, in <module>
    'Release'
  File "./jenkins.py", line 31, in do_call
    subprocess.check_call(args, env=os.environ)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'build.py'
```
This `build.py` file does not seem to be included in the repo.

**Comment by ruslo** [comment]
It's from https://github.com/ruslo/polly/tree/master/bin

I've updated README, see "Polly scripts should be in PATH":
* https://github.com/forexample/ios-dynamic-framework
